FROM python:3.11

WORKDIR /app

COPY ./apps/jobs_microservice/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY ./apps/jobs_microservice/ .

ENV FLASK_APP=jobs.py

EXPOSE 5001

CMD ["flask", "run", "--host=0.0.0.0", "--port=5001"]