FROM python:3.11

WORKDIR /app

COPY ./apps/api_microservice/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY ./apps/api_microservice/ .

ENV FLASK_APP=api.py

EXPOSE 5000

CMD ["flask", "run", "--host=0.0.0.0", "--port=5000"]